#!/usr/bin/env pwsh

Write-Host -Object "Running Pre-Push hook"

$pesterInstalled = Get-Command -Name Invoke-Pester -ErrorAction SilentlyContinue
if ($null -eq $pesterInstalled) {
  Write-Error -Message 'Pester is not installed but is required to run QA. Fix by installing Pester (Install-Module Pester)' -ErrorAction Stop
}

Write-Host -Object "Running QA unit tests"
$qaResult = Invoke-Pester -Script ./src/ARM/tests/qa/QA.tests.ps1 -Show Describe, Failed -PassThru
if ( $qaResult.FailedCount -gt 0 ) {
  Write-Error -Message 'QA tests errors were found' -ErrorAction Stop
}

Write-Host -Object "Running Common tests"
$commonResult = Invoke-Pester -Script ./src/ARM/tests/common/Common.Tests.ps1 -Show Describe, Failed -PassThru
if ( $commonResult.FailedCount -gt 0 ) {
  Write-Error -Message 'PSScriptAnalyzer test errors were found' -ErrorAction Stop
}

Write-Host -Object "Running Integration tests"
$intResult = Invoke-Pester -Script ./src/ARM/tests/integration/Integration.tests.ps1 -Show Describe, Failed -PassThru
if ( $intResult.FailedCount -gt 0 ) {
  Write-Error -Message 'Integration test errors were found' -ErrorAction Stop
}
