# Environment specific variables

variables:
- name: serviceConnection
  value: azureInternal

- name: environmentName
  value: int

- name: subscriptionId
  value: f2d85cf0-b21c-4794-a259-f508c89d08c2

- name: subscriptionName
  value: EROSHOKO MSFT Azure

- name: location
  value: eastus2

- name: resourceGroupName
  value: core-rg
