# Environment specific variables

variables:
- name: serviceConnection
  value: my-spn-connection

- name: environmentName
  value: dev

- name: subscriptionId
  value: xxxxx-b21c-4794-a259-xxxxxx

- name: location
  value: eastus
