parameters:
  vmImage: ''
  serviceConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  environmentName: ''

jobs:
- job: Teardown
  displayName: Teardown ${{ upper(parameters.environmentName) }}
  pool:
    vmImage: "${{ parameters.vmImage }}"
  steps:
  - checkout: self
  - task: AzurePowerShell@5
    displayName: Teardown environment
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: 'Latest'
      ScriptType: 'InlineScript'
      Inline: |
        . $(baseWorkingDirectory)/tests/Pester.ps1

        Invoke-ARMDeployment -Scope "subscription" -ResourceGroupName $(resourceGroupName) -SubscriptionId $(subscriptionId) -TeardownEnvironment
