parameters:
  vmImage: ''
  serviceConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  environmentName: ''

jobs:
- job: Teardown
  displayName: Teardown ${{ upper(parameters.environmentName) }}
  pool:
    vmImage: "${{ parameters.vmImage }}"
  steps:
  - checkout: self
  - task: AzurePowerShell@5
    displayName: Delete RG - ${{ parameters.resourceGroupName }}
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: 'Latest'
      ScriptType: 'InlineScript'
      Inline: |
        # load module
        . $(baseWorkingDirectory)/internal/scripts/preimport.ps1 && . $(baseWorkingDirectory)/tests/Pester.ps1 && . $(baseWorkingDirectory)/internal/functions/deploy/Invoke-DestroyEnvironment.ps1

        Invoke-DestroyEnvironment -Scope "subscription" -ResourceGroupName ${{ parameters.resourceGroupName }} -SubscriptionId $(subscriptionId)
