parameters:
  vmImage: ''

jobs:
  - job: 'Prerequisites'
    pool:
      vmImage: $(vmImage)
    steps:
      - checkout: self
      - pwsh: |
          . $(baseWorkingDirectory)/internal/scripts/preimport.ps1
        displayName: 'Import Modules'

  - job: Install
    displayName: 'Install Bicep'
    dependsOn: Prerequisites
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Bash@3
      displayName: 'Install latest AZ bicep CLI'
      inputs:
        targetType: 'inline'
        script: |
          az bicep install

  - job: Build
    displayName: 'Build Bicep'
    dependsOn: Install
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Bash@3
      displayName: 'Build ARM Template from bicep file'
      inputs:
        targetType: 'inline'
        script: |
          az bicep build --file '$(bicepDirectory)/main.bicep'

    - task: CopyFiles@2
      displayName: Copy build artifacts
      inputs:
        sourceFolder: '$(bicepDirectory)'
        contents: '*.json'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish build artifacts
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: deployment
