parameters:
  resourceGroupName: ''
  environmentName: ''
  region: ''
  prefix: ''
  vmImage: ''
  serviceConnection: ''
  validateDeploymentType: ''

jobs:
  - job: Deploy_${{ parameters.environmentName }}
    displayName: 'Deploy'
    pool:
      vmImage: "${{ parameters.vmImage }}"
    steps:
      - checkout: self

      - task: DownloadBuildArtifacts@0
        displayName: "Download artifacts"
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: "deployment"
          downloadPath: "$(Build.ArtifactsDirectory)"

      - task: AzurePowerShell@5
        displayName: "Deploy Bicep"
        inputs:
          azureSubscription: "$(serviceConnection)"
          ScriptType: "InlineScript"
          Inline: |
            # load module
            . $(baseWorkingDirectory)/tests/Pester.ps1

            $deploymentArgs = @{}
            if ('${{ parameters.validateDeploymentType }}' -eq 'validate') {
              $deploymentArgs += @{
                Validate = $true
              }
            } elseif ('${{ parameters.validateDeploymentType }}' -eq 'validateWhatIf') {
                $deploymentArgs += @{
                  ValidateWhatIf = $true
                }
              }
            }

            $deploymentArgs += @{
              Scope                     = "subscription"
              SubscriptionId            = "$(subscriptionId)"
              DeploymentTemplate        = "$(bicepDirectory)/main.json"
              ResourceGroupName         = "$(resourceGroupName)"
              DeploymentScope           = "resourcegroup"
              TemplateParameterFilePath = "$(bicepDirectory)/main.parameters.${{ parameters.environmentName }}.json"
              DefaultDeploymentRegion   = "$(region)"
            }

            Invoke-ARMDeployment @deploymentArgs
          azurePowerShellVersion: "LatestVersion"
