parameters:
  resourceGroupName: ''
  environmentName: ''
  location: ''
  prefix: ''
  vmImage: ''
  serviceConnection: ''
  validateDeploymentType: ''

jobs:
  - job: Deploy_${{ parameters.environmentName }}
    displayName: 'Deploy'
    pool:
      vmImage: "${{ parameters.vmImage }}"
    steps:
      - checkout: self

      - task: DownloadBuildArtifacts@0
        displayName: "Download artifacts"
        inputs:
          buildType: "current"
          downloadType: "single"
          artifactName: "deployment"
          downloadPath: "$(Build.ArtifactsDirectory)"

      - task: AzurePowerShell@5
        displayName: "Deploy Bicep"
        inputs:
          azureSubscription: "$(serviceConnection)"
          ScriptType: "InlineScript"
          Inline: |
            # load module
            . $(baseWorkingDirectory)/internal/scripts/preimport.ps1 && . $(baseWorkingDirectory)/tests/Pester.ps1

            $deploymentArgs = @{}
            if ('${{ parameters.validateDeploymentType }}' -eq 'validate') {
              $deploymentArgs += @{
                Validate = $true
              }
            } elseif ('${{ parameters.validateDeploymentType }}' -eq 'validateWhatIf') {
              $deploymentArgs += @{
                ValidateWhatIf = $true
              }
            } else {
              Write-Host "##[debug]Deployment will now begin to environment - '${{ parameters.environmentName }}'"
            }

            $deploymentArgs += @{
              Scope                     = "subscription"
              SubscriptionId            = "$(subscriptionId)"
              TemplateFilePath          = '$(Build.ArtifactsDirectory)/deployment/main.json'
              TemplateParameterFilePath = "$(bicepDirectory)/main.parameters.${{ parameters.environmentName }}.json"
              Location                  = "$(location)"
            }

            Invoke-ARMDeployment @deploymentArgs
          azurePowerShellVersion: "LatestVersion"
