# Summary: Invokes CCP pipeline job
# Description: This pipeline job will invoke the CCP pipeline to deploy any resources that requires post deployment configuration
# Eg: DNS records, firewall rules, network rules etc.

parameters:
  vmImage: ''
  poolName: ''
  serviceConnection: ''
  resource: ''
  templateParameterFilePath: ''

jobs:
- job: Deploy_${{ parameters.resource }}
  displayName: Deploy_${{ parameters.resource }}
  pool:
    ${{ if ne(parameters.vmImage, '') }}:
      vmImage: ${{ parameters.vmImage }}
    ${{ if ne(parameters.poolName, '') }}:
      name: ${{ parameters.poolName }}
  steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: 'Deploy_${{ parameters.resource }}'
    inputs:
      azureSubscription: '${{ parameters.serviceConnection }}'
      ScriptType: 'FilePath'
      ScriptPath: '$(System.DefaultWorkingDirectory)/external/scripts/trigger-ccp-pipeline.ps1'
      ScriptArguments: '-ParameterFile "${{ parameters.templateParameterFilePath }}" -PipelineStage "buildAndDeploy"'
      azurePowerShellVersion: 'LatestVersion'
