parameters:
  vmImage: ''
  poolName: ''
  serviceConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  environmentName: ''

jobs:
- job: Teardown
  displayName: Teardown ${{ upper(parameters.environmentName) }}
  pool:
    ${{ if ne(parameters.vmImage, '') }}:
      vmImage: ${{ parameters.vmImage }}
    ${{ if ne(parameters.poolName, '') }}:
      name: ${{ parameters.poolName }}
  steps:
  - checkout: self
  - task: AzurePowerShell@5
    displayName: Delete RG - ${{ parameters.resourceGroupName }}
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: 'Latest'
      ScriptType: 'InlineScript'
      Inline: |
        # load module
        . $(baseWorkingDirectory)/tests/Pester.ps1

        Invoke-DestroyEnvironment -DeploymentScope "subscription" -ResourceGroupName ${{ parameters.resourceGroupName }} -SubscriptionId $(subscriptionId)
