parameters:
  serviceConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  resourceProviders: ''
  resourceProviderFeatures: ''

jobs:
- job: ResourceProviders
  displayName: Register resource providers
  steps:
  - checkout: none
  - task: AzurePowerShell@5
    displayName: Register resource providers
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: 'Latest'
      ScriptType: 'InlineScript'
      Inline: |
        $scopeObject = New-ARMScope -ResourceGroupName $(resourceGroupName) -SubscriptionId $(subscriptionId)
        Register-ARMResourceProvider -ResourceProviders $(resourceProviders) -ScopeObject $scopeObject

  - task: AzurePowerShell@5
    displayName: Register resource provider features
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: 'Latest'
      ScriptType: 'InlineScript'
      Inline: |
        $scopeObject = New-ARMScope -ResourceGroupName $(resourceGroupName) -SubscriptionId $(subscriptionId)
        Register-ARMProviderFeature -ProviderFeatures $(resourceProviderFeatures) -ScopeObject $scopeObject
