parameters:
  vmImage: ''
  serviceConnection: ''
  subscriptionId: ''
  resourceGroupName: ''
  environmentName: ''

jobs:
- job: Teardown
  displayName: Teardown ${{ parameters.environmentName }}
  pool:
    vmImage: "${{ parameters.vmImage }}"
  steps:
  - checkout: self
  - task: AzurePowerShell@5
    displayName: Teardown environment
    inputs:
      azureSubscription: $(serviceConnection)
      azurePowerShellVersion: 'Latest'
      ScriptType: 'InlineScript'
      Inline: |
        Invoke-ARMDeployment -Scope "resourcegroup" -ResourceGroupName $(resourceGroupName) -SubscriptionId $(subscriptionId) -TeardownEnvironment
