# Summary: Invokes CCP pipeline job
# Description: This pipeline job will invoke the CCP pipeline to deploy any resources that requires post deployment configuration
# Eg: DNS records, firewall rules, network rules etc.

parameters:
  serviceConnection: ''
  resource: ''
  templateParameterFilePath: ''

jobs:
- job: InvokeCCP_${{ parameters.resource }}
  displayName: InvokeCCP_${{ parameters.resource }}
  steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: 'Deploy_${{ parameters.resource }}'
    inputs:
      azureSubscription: '${{ parameters.serviceConnection }}'
      ScriptType: 'FilePath'
      ScriptPath: '$(System.DefaultWorkingDirectory)/external/scripts/trigger-ccp-pipeline.ps1'
      ScriptArguments: '-ParameterFile "${{ parameters.templateParameterFilePath }}" -PipelineStage "buildAndDeploy"'
      azurePowerShellVersion: 'LatestVersion'
